version: '3.4'

services:
  php:
    container_name: 'app-php_fpm'
    network_mode: bridge
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/php:/usr/local/etc/php:ro,cached
      - .:/app:rw,cached
      - ./var:/app/var:rw,delegated
    expose:
      - 9000
    user: '1000'

  nginx:
    container_name: 'app.docker'
    network_mode: bridge
    build: .docker/nginx
    ports:
      - 80:80
    volumes:
      - ./public:/app/public:ro
      - ./.docker/nginx/etc/nginx:/etc/nginx:ro,cached
    links:
      - php